data:
  batch_size: 64
  target_idx: 4
  seed: 0
  data_debug: False
  size_debug: 500

model:
  model_type: "gcn"
  hidden_dim: 64
  num_layers: 2

training:
  n_epochs: 50
  lr: 0.001
  patience: 10
  min_delta: 0.001
  optimizer_type: "adam"
  criterion_type: "l1"

logging:
  demo_project: "gnn-molecule-prediction-demos"
  gpu_debug: True
  config_debug: True