n_epochs: 50
lr: 0.001
batch_size: 64
target_idx: 4
seed: 0
patience: 10
min_delta: 0.001
demo_project: "gnn-molecule-prediction-demos"

model_type: "gcn"
hidden_dim: 64
num_layers: 2

gpu_debug: True
config_debug: True

optimizer_type: "adam"
criterion_type: "l1"